### ISSUE TITLE
Different behavior in iOS and Android when switching apps

### ISSUE THREAD

**Issue by adminant** [ThexXTURBOXx/flutter_web_auth_2#94] opened 2024-01-12 10:30 UTC
### Description

in iOS when auth browser window is open and we switch to other app and switch back, browser remains active and we can continue authenticating.
In Android when we switch to another app and back, browser window is disappeared, and 'user canceled login' error is received.
No any flags are used when calling authenticate.
I think this is not intended behavior, because 
1) iOS and Android behavior is different
2) In Android user can't switch app to copy/paste credentials, which is bad user experience, so we receive bad reviews

I tried to google this bug and seems it is very common in other auth and 3ds libraries, and is related to Chrome Custom Tabs, but it is unclear how to avoid closing tab when switching apps.

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
      final result = await FlutterWebAuth2.authenticate(
        url: url,
        callbackUrlScheme: url-scheme,
      );

### Exception or Error

User canceled login event after switching app

### Expected Behaviour

Browser window remains on top after switching app

### Device

Android simulator, Google Pixel. Xiaomi, etc

### OS

iOS 15.5

### Browser

none

### Flutter version

3.3.10

### flutter_web_auth_2 version

3.1.1

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment] 2024-01-12 10:32
Duplicate of #93

**Closed by ThexXTURBOXx** 2024-01-12 10:32 UTC
Labels: bug
