### ISSUE TITLE
Clear webview cache

### ISSUE THREAD

**Issue by zanelladev** [ThexXTURBOXx/flutter_web_auth_2#66] opened 2023-09-12 19:13 UTC
I'm facing a problem in a code, I'm using the library to log in, working! But to log out, I need to clear the cache and cookies from the last login, I haven't found a way.

Do you already have a feature for this? Any idea how to solve this?

**Comment by ThexXTURBOXx** [comment] 2023-09-12 19:32
Duplicate of #49.
Basically, you cannot easily clear the cookies and/or cache currently.
However, if there is an endpoint which performs the logout process, you should be able to call that using just another call to `authenticate`

**Closed** 2023-09-12 19:32 UTC
Labels: enhancement
