### ISSUE TITLE
[Bug]: Android auth web session terminates when opening other apps

### ISSUE THREAD

**Issue by CKunhardt** [ThexXTURBOXx/flutter_web_auth_2#142] opened 2024-11-07 22:14 UTC
### Description

Reposting an identical issue with LinusU's flutter_web_auth -- on Android, we're noticing that the authentication modal is closing when users switch tabs, say, to retrieve a two-factor authentication code or an OTP. By the time they switch back to the Flutter app, the popup window is gone, and they're effectively blocked from ever actually entering a code, unless they retrieve it on a different device or capture it from the notification.

Original issue: https://github.com/LinusU/flutter_web_auth/issues/158

### Minimal Reproduction

Steps to reproduce the behaviour:

1. Use the following code:
    ```dart
    final result = await FlutterWebAuth2.authenticate(
        url: url,
        callbackUrlScheme: Uri.parse(callbackUrl).scheme,
        options: const FlutterWebAuth2Options(
          preferEphemeral: true,
          intentFlags: ephemeralIntentFlags,
        ),
      );

      final credential = await flow.callback(
        Uri.parse(result).queryParameters,
      );

      return credential;
    ```
2. Open app on Android device and trigger authentication modal
3. Switch tabs to another app without closing the Flutter app
4. Switch back to the Flutter app

### Exception or Error

Authentication modal is closed on return to app

### Expected Behaviour

Authentication modal stays available for user interaction after switching back to the app

### Device

Pixel 9 Pro XL

### OS

Android 15

### Browser

Stock (Chrome Custom Tabs)

### Flutter version

3.24.3

### flutter_web_auth_2 version

3.1.1

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment] 2024-11-08 07:17
Duplicate of #33 
I have not found any fix for the issue, but the `intentFlags` are completely adjustable and hence, the user can choose a combination that works for them.
Maybe some combination does what you want it to do, but I have not found one yet, sadly.

**Closed by ThexXTURBOXx** 2024-11-08 07:17 UTC
Labels: bug
