### ISSUE TITLE
[Bug]: MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)

### ISSUE THREAD

**Issue by sirawatGG** [ThexXTURBOXx/flutter_web_auth_2#126] opened 2024-09-09 15:11 UTC
### Description

Hello there, I received an error message on the client's phone. However, after they updated their iOS to the latest version, they were able to authenticate successfully.

I'm unsure if updating the beta version would resolve this issue. Additionally, I understand that the new approach you mentioned only affects Linux and Windows, and not mobile devices.

### Minimal Reproduction

-

### Exception or Error

MissingPluginException(No implementation found for method authenticate on channel flutter_web_auth_2)

### Expected Behaviour

Should authen successfully

### Device

Iphone13

### OS

Ios 16.2.0

### Browser

-

### Flutter version

3.22.2

### flutter_web_auth_2 version

3.1.2

### Checklist

- [X] I have read and followed the **entire** [troubleshooting guide](https://github.com/ThexXTURBOXx/flutter_web_auth_2#troubleshooting) and it has not provided the solution I need.
- [X] I have provided all the information I can.

**Comment by ThexXTURBOXx** [comment] 2024-09-09 16:23
I guess this could be a race condition caused by https://github.com/flutter/flutter/issues/98473
In order to be sure that the correct implementation can be found, `DartPluginRegistrant.ensureInitialized()` needs to be invoked first, probably.

**Comment by sirawatGG** [comment] 2024-09-10 00:21
Thank you @ThexXTURBOXx very much, I will try

**Comment by ThexXTURBOXx** [comment] 2024-09-10 10:52
I will close this as this is not really related to `flutter_web_auth_2`

**Closed by ThexXTURBOXx** 2024-09-10 10:52 UTC
Labels: bug

**Comment by oranorr** [comment] 2024-11-22 04:45
Hello!
For me there is still an issue authentication method fails on iOS 15.5 and 16.7, but works perfectly well on higher versions like 18.1. 

```
try {

        result = await FlutterWebAuth2.authenticate(
          url: authUrl,
          callbackUrlScheme: callbackUrl,
        );
      } catch (e) {
        print("Authentification failed or error occured:: $e");
        return const Left(AuthenticationFailure());
      }
```


Im not quite sure what additional data I should provide.

**Comment by ThexXTURBOXx** [comment] 2024-11-22 05:55
@oranorr This is expected and has nothing to do with this issue. If you want to support older iOS versions, use version 3.x of this package and read the README

**Comment by oranorr** [comment] 2024-11-22 06:32
@ThexXTURBOXx of course I read README. Tried with 3.0.0 and 2.2.1 versions — still no luck.

**Comment by ThexXTURBOXx** [comment] 2024-11-22 06:41
Then, open a new issue and provide more data

**Comment by ThexXTURBOXx** [comment] 2024-11-22 06:44
Then, please open a new issue and provide more data as required by the template. I am 99% sure that this is not an issue if this package, though, as there have been no recent bug reports regarding such issues and in the past, pretty much all of them have been an issue with the setup.

**Comment by oranorr** [comment] 2024-11-22 07:01
@ThexXTURBOXx alright, it seems, I found the solution. 

The problem was, as per your README:
> _To use multiple scopes with Google, you need to encode them as a single string, separated by spaces_

Having multiple scopes, forming String from them with `'$scopes.join(" ")',` failed me on earlier iOs. But this [comment](https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/9#issuecomment-1326316264) hinted me to figure out that maybe issue **is** in spaces. 

So I boldly changed 
`'$scopes.join(" ")',`
to 
`'$scopes.join("%20")',`

Which is working perfectly well on iOs 15.5, 17.5 and higher, using even latest 4.0.1 version of this package. 


I hope it will help someone.
Thank you for your time

**Comment by hungdt2nf** [comment] 2024-11-26 10:52
> @ThexXTURBOXx alright, it seems, I found the solution.
> 
> The problem was, as per your README:
> 
> > _To use multiple scopes with Google, you need to encode them as a single string, separated by spaces_
> 
> Having multiple scopes, forming String from them with `'$scopes.join(" ")',` failed me on earlier iOs. But this [comment](https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/9#issuecomment-1326316264) hinted me to figure out that maybe issue **is** in spaces.
> 
> So I boldly changed `'$scopes.join(" ")',` to `'$scopes.join("%20")',`
> 
> Which is working perfectly well on iOs 15.5, 17.5 and higher, using even latest 4.0.1 version of this package.
> 
> I hope it will help someone. Thank you for your time

Thanks. This work for me.

**Comment by sirawatGG** [comment] 2024-12-17 05:17
@oranorr I see, yes I think this is the problem.
Thank you
